import sys

try:
    print('Program is running...')
    sys.exit

except Exception as e:
    print(f'An error occurred: {e}')